name: fldraw
description: "The open-source tldraw alternative for building infinite canvas apps in Flutter."
version: 0.1.0
homepage: "https://github.com/fldraw/fldraw"
repository: "https://github.com/fldraw/fldraw"
issue_tracker: "https://github.com/fldraw/fldraw/issues"

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_shaders: ^0.1.3
  keymap: ^0.0.92
  uuid: ^4.5.1

  perfect_freehand: ^2.3.2
  flutter_svg: ^2.2.0
  vector_graphics: ^1.1.19
  shadcn_flutter: ^0.0.37

  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/src/gen
  assets:
    outputs:
      package_parameter_enabled: true
  integrations:
    image: true
    flutter_svg: true

flutter:
  shaders:
    - shaders/grid.frag

  assets:
    - assets/icons/

topics:
  - diagram
  - canvas
  - whiteboard
  - drawing
  - tldraw
